version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=development
    env_file:
      - ./src/.env
    command: node src/index.js
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db